name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t my-web-app:${{ github.sha }} .

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image to DockerHub
        run: |
          docker tag my-web-app:${{ github.sha }} mydockerhubuser/my-web-app:${{ github.sha }}
          docker push mydockerhubuser/my-web-app:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: SSH into Cloud VM and Deploy App
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker pull mydockerhubuser/my-web-app:${{ github.sha }}
            sudo docker stop my-web-app || true
            sudo docker rm my-web-app || true
            sudo docker run -d -p 80:3000 --name my-web-app mydockerhubuser/my-web-app:${{ github.sha }}
